### ISSUE TITLE
Improved Menu

### ISSUE THREAD

**Issue by mbeisel** [PlanQK/workflow-modeler#64]
**Problem Statement:**
The current Menu takes a lot of space and is limited in its functionality. Hence, we suggest adding a classic dropdown menu bar and keeping the most used functionalities (new, open, save, save as) as icons

The file dropdown shall include:
- New File
- Open File
- Save File
- Save File as BPMN
- Save File as SVG
- Save File as PNG
- Save all Files as ...

The configuration dropdown shall contain the general editor, as well as plugin configurations categories and on selection open a popup with the corresponding configurations, e.g., 
![grafik](https://github.com/PlanQK/workflow-modeler/assets/19931367/927f9f92-ff41-4131-89fe-1595bd205e88)
Configuration values are values, which are rarely changed, meaning that commonly changed values such as the filename shall not be included in the configurations tab. If there are any uncertainties about this, please comment below.

**Sketch:**
![grafik](https://github.com/PlanQK/workflow-modeler/assets/19931367/143dba9a-9d8e-4c17-a157-e12a7c6e8634)
Note: the save and save as icon should be distinguishable

**Comment by miwurster** [comment]
For the PlanQK integration, we do not need anything related to save or open files. Instead, we just a save operation that emits an event containing the latest model data. We gonna use an event listener to catch such events in order to save the data in our backend.

Further, we also don't need the options "Deploy Workflow", "QHAna", and "QuantMe". In general, it would be nice if we can enable/disable certain menu items when initialising the workflow modeler component in our frontend Vue project.
